"""database update

Revision ID: 05ab8ed6f3d8
Revises: ec650420275d
Create Date: 2026-07-24 02:28:30.883231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ab8ed6f3d8'
down_revision: Union[str, None] = 'ec650420275d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('chunk_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_chunk_project_id'), table_name='chunks')
    op.create_unique_constraint('uq_chunk_asset_id_chunk_hash', 'chunks', ['chunk_asset_id', 'chunk_hash'])
    op.create_unique_constraint('uq_chunk_project_id_chunk_hash', 'chunks', ['chunk_project_id', 'chunk_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunk_project_id_chunk_hash', 'chunks', type_='unique')
    op.drop_constraint('uq_chunk_asset_id_chunk_hash', 'chunks', type_='unique')
    op.create_index(op.f('ix_chunk_project_id'), 'chunks', ['chunk_project_id'], unique=False)
    op.drop_column('chunks', 'chunk_hash')
    # ### end Alembic commands ###
