"""adding new col in chat history

Revision ID: 147980a59dad
Revises: e02e7e0d226a
Create Date: 2026-07-13 01:14:09.596212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147980a59dad'
down_revision: Union[str, None] = 'e02e7e0d226a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('query', sa.String(), nullable=False))
    op.add_column('chat_history', sa.Column('answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'answer')
    op.drop_column('chat_history', 'query')
    # ### end Alembic commands ###
