"""composite_unique_asset_hash_project

Revision ID: 2972aaf9a0a2
Revises: 43862b85b31a
Create Date: 2026-07-22 22:33:07.804639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2972aaf9a0a2'
down_revision: Union[str, None] = '43862b85b31a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assets_file_hash_key'), 'assets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('assets_file_hash_key'), 'assets', ['file_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
