"""composite_unique_asset_hash_project

Revision ID: 43862b85b31a
Revises: 1b388f29a34c
Create Date: 2026-07-22 22:22:48.139406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43862b85b31a'
down_revision: Union[str, None] = '1b388f29a34c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_asset_hash_project', 'assets', ['file_hash', 'asset_project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_hash_project', 'assets', type_='unique')
    # ### end Alembic commands ###
