"""database update

Revision ID: 6165fb9d8e20
Revises: 05ab8ed6f3d8
Create Date: 2026-07-24 03:13:46.607149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6165fb9d8e20'
down_revision: Union[str, None] = '05ab8ed6f3d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_chunk_asset_id_chunk_hash'), 'chunks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_chunk_asset_id_chunk_hash'), 'chunks', ['chunk_asset_id', 'chunk_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
