"""database update

Revision ID: 64b8ba93f917
Revises: ef4283669e1d
Create Date: 2026-07-24 04:21:16.667332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b8ba93f917'
down_revision: Union[str, None] = 'ef4283669e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_chunk_asset_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_chunk_asset_id_fkey'), 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'])
    # ### end Alembic commands ###
