"""adding new col

Revision ID: 7e1d59cbb8ec
Revises: 147980a59dad
Create Date: 2026-07-22 21:18:41.569058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e1d59cbb8ec'
down_revision: Union[str, None] = '147980a59dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'assets', ['file_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    op.drop_column('assets', 'file_hash')
    # ### end Alembic commands ###
