"""composite_unique_asset_hash_project

Revision ID: 885c8d7774ee
Revises: dc8d1595a2f2
Create Date: 2026-07-23 01:02:12.746712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '885c8d7774ee'
down_revision: Union[str, None] = 'dc8d1595a2f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_project_id'), table_name='assets')
    op.drop_constraint(op.f('uq_asset_hash_project'), 'assets', type_='unique')
    op.create_unique_constraint('uq_asset_project_id_hash', 'assets', ['asset_project_id', 'file_hash'])
    op.create_unique_constraint('uq_asset_project_id_name', 'assets', ['asset_project_id', 'asset_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asset_project_id_name', 'assets', type_='unique')
    op.drop_constraint('uq_asset_project_id_hash', 'assets', type_='unique')
    op.create_unique_constraint(op.f('uq_asset_hash_project'), 'assets', ['file_hash', 'asset_project_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_asset_project_id'), 'assets', ['asset_project_id'], unique=False)
    # ### end Alembic commands ###
