"""composite_unique_asset_hash_project

Revision ID: dc8d1595a2f2
Revises: 2972aaf9a0a2
Create Date: 2026-07-22 22:34:40.024455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8d1595a2f2'
down_revision: Union[str, None] = '2972aaf9a0a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
