"""create chat history table

Revision ID: e02e7e0d226a
Revises: b15398d07d9b
Create Date: 2026-07-12 22:30:30.383386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02e7e0d226a'
down_revision: Union[str, None] = 'b15398d07d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('chat_history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_history_uuid', sa.UUID(), nullable=False),
    sa.Column('chat_project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_history_id'),
    sa.UniqueConstraint('chat_history_uuid')
    )
    op.create_index('ix_chat_project_id', 'chat_history', ['chat_project_id'], unique=False)
    op.drop_constraint('assets_asset_project_id_fkey', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'projects', ['asset_project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint('chunks_chunk_project_id_fkey', 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'projects', ['chunk_project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key('chunks_chunk_project_id_fkey', 'chunks', 'projects', ['chunk_project_id'], ['project_id'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key('assets_asset_project_id_fkey', 'assets', 'projects', ['asset_project_id'], ['project_id'])
    op.drop_index('ix_chat_project_id', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
